### PR TITLE
GTX 1080 Ti results

### PR DESCRIPTION
**Pull request by Shmuma**

### CODE REVIEW

**Comment by jcjohnson** [comment]
Awesome, thanks! Can you change the name from "GTX 1080 Titan" to "GTX 1080 Ti"?

**Comment by Shmuma** [comment]
Sure, done.

**Comment by jcjohnson** [comment]
Can you also add a sentence about the configuration of the machine (CPU, RAM, and OS) similar to the details for the other GPUs?

**Comment by jcjohnson** [comment]
I don't suppose you also have a Titan Xp to benchmark =p

**Comment by Shmuma** [comment]
Yep. I'd rather bought second Ti :). In fact, I've always though that Ti stands for Titan, and it's just an abbreviation.

**Comment by jcjohnson** [comment]
Getting a second 1080 Ti is probably a better use of your money ;)

I think the "Ti" branding is supposed to suggest Titan, but it's not an official abbreviation as far as I know.

**Pull request merged**
